### ISSUE TITLE
[ENHANCEMENT] 'ntrboot.firm' payload support

### ISSUE THREAD

**Issue by annson24** [kitling/ntrboot_flasher#14]
boot ntrboot.firm payload instead of boot.firm payload. Or, had it first search for the ntrboot.firm payload, if none, proceed in booting boot.firm payload.

**Comment by kitling** [comment]
Out of scope for this repository. boot9strap handles payload loading, not the flasher itself. https://github.com/SciresM/boot9strap

**Comment by hedgeberg** [comment]
Also worth poiting out, if you really want this you can easily build b9s for yourself with a changed filepath. I did this for testing the other day. You just need to grep the repo for boot.firm and change it to whatever you want before building
