### ISSUE TITLE
Less of an issue just an r4 question

### ISSUE THREAD

**Issue by minerplays** [kitling/ntrboot_flasher#2]
Dear anyone whom is cleverer than me,
Does unfinished for the r4 dual core mean I can't use it or does it mean it is usable but less stable?
Do I need a r4i gold or ak2i at the moment or is my 2016 r4 sdhc dual core useable

**Comment by Hikari-chin** [comment]
It can't be used. But please, don't use Github issues for tech support. That is not its purpose.

**Comment by kitling** [comment]
You cannot use it.

I did some reverse engineering on an updater for it after quibsica (I think that's how it's spelled?) showed up in #Cakey and got some help figuring out the encryption scheme for part of flash.

Then, of course, I didn't have time to finish.
