### ISSUE TITLE
ntrboot_flasher can dump Acekard 2i HW-81 but not inject anything to it - DUPLICATED

### ISSUE THREAD

**Issue by cakehonolulu** [kitling/ntrboot_flasher#20]
So, running ntrboot_flasher on my Acekard 2i HW-81 (R4i Ultra clone) works, whenever I want to dump the flashcard's internal memory, there are no problems. But whenever I try to inject the ntrboothax into it, it doesn't start and it stays at "Injecting..." indefinitely.

Some information:
ChipID: 000040C8
HW Rev: 81818181
Detected: Acekard 2i HW-81

I can provide the card's dump without any problem (Verified it has content with a hex viewer)

**Comment by Siogenon** [comment]
Same problem here : https://github.com/kitling/ntrboot_flasher/issues/12
