### ISSUE TITLE
[QUESTION] Is the R4 Upgrade Gold Pro (2016) flashcard compatible?

### ISSUE THREAD

**Issue by GrenderG** [kitling/ntrboot_flasher#21]
I'm not sure if this flashcard is compatible so I thought this would be a right place to ask. 😄 

![r4igold](https://user-images.githubusercontent.com/8654362/29327222-bec656f2-81ee-11e7-8047-bdf40773c57d.png)

Thanks in advance!

**Comment by y0shimari0** [comment]
Just try it and report back if it works or not. AKA we dont know

**Comment by GrenderG** [comment]
@y0shimari0 I can't try it atm, I opened this issue in case someone (apart from the devs) has tried it.

**Comment by kitling** [comment]
What @y0shimari0 said. Just so you know, if it isn't compatible, this isn't the place to ask for someone to work on it. Read the README and follow the links, in that case.

It probably *isn't* compatible, but you never know.

**Comment by lomejor18** [comment]
@kitling is it possible for you to make an app for flashing generic flashcarts? (for recovering purpose)

some time ago, i broke a chinese flashcart when tried to install YSmenu...
i would like to dump the flash from another flashcart (same model) and inject it on the broken one...
or that's nor possible?
thanks for your answer...

**Comment by hedgeberg** [comment]
If we could do that we'd be able to support every flashcart already. We don't know the flash r/w commands, meaning we simply can't do that.

**Comment by kitling** [comment]
@lomejor18 That's... kind of the point of getting everyone to help. This isn't generic yet, but with some time and patience, we can make this work on a lot of carts.

**Comment by Hikari-chin** [comment]
Read the README next time.
