### ISSUE TITLE
ntrboot flasher works on a R4i Gold 3DS Deluxe Edition too!

### ISSUE THREAD

**Issue by doctahoo** [kitling/ntrboot_flasher#22]
Hi,

This is not an issue, but rather a confirmation.

Could you please add the R4i Gold 3DS Deluxe Edition to your list of ntrboothax compatible cards?

Thanks!

**Comment by hedgeberg** [comment]
As in it works as-is? Can you submit an issue with the CID, HW rev, a picture of the cart, and the reseller you bought it from over at the flashcart_core repo? Thanks!!
