### ISSUE TITLE
R4i SDHC Support please?

### ISSUE THREAD

**Issue by R4i-SDHC-For-NTRBoothax-Please** [kitling/ntrboot_flasher#25]
Is it somehow possible you will attempt to add r4i sdhc support r4i-sdhc.com or should i order a r4i gold and wait 3 weeks for shipping

**Comment by kitling** [comment]
Please read the README next time.

In short, it's possible, idk if it's going to happen within 3 weeks. However, **This is not the correct place for this kind of issue, and of you had read the README you would know that**.
