### ISSUE TITLE
Not an issue but more of an idea on how to get ANY card's code stuff

### ISSUE THREAD

**Issue by QuoteStrife** [kitling/ntrboot_flasher#26]
![image](https://user-images.githubusercontent.com/31014068/29440809-c37e57e6-8395-11e7-97cf-2d9e4a9fe592.png)

This is an idea i am putting in the ntrboot issue page as a way for people with actual skill to try out my idea.    Can we not use powerslaves to get into the card and reverse engineer it?

**Comment by kitling** [comment]
That is one tool we have available to us, indeed. We still need *something* to give us an idea of how to read/erase/write flash.

**Comment by hedgeberg** [comment]
I'm actually streaming working on this with the scds2+. Our process thus
far has been: dump the spi flash using flashrom on an rpi to get the flash,
look for any obvious code, then start reverse engineering any software
available to us, like firmware updaters, and then if all else fails we have
a flash backup and can write an app to fuzz the cart with magic numbers.

**Comment by QuoteStrife** [comment]
oh well is there a way we can contact r4isdhc.com for that _something_

**Comment by QuoteStrife** [comment]
also, did you guys try looking for an older model that may have something we can use and then try it on the r4i sdhc

**Comment by Hikari-chin** [comment]
This is not an appropriate use of the issues page.
