### ISSUE TITLE
R4 gold 3DS RTS "Supported Cartridge not Detected!"

### ISSUE THREAD

**Issue by Ethydee** [kitling/ntrboot_flasher#27]
I get this error when dumping flash.
Below are pics of the error and my card.

![win_20170818_21_46_35_pro](https://user-images.githubusercontent.com/26497270/29482841-ef812584-845e-11e7-8060-9633323ff143.jpg)
![win_20170818_21_47_13_pro](https://user-images.githubusercontent.com/26497270/29482842-f74d6714-845e-11e7-98bb-320efe045353.jpg)
![win_20170818_21_47_19_pro](https://user-images.githubusercontent.com/26497270/29482843-f74f5196-845e-11e7-9e21-d6eddd56a592.jpg)

**Comment by mariogamer2** [comment]
It's not the same model. Also @dark-samus is working on it.

PS. Read the Readme. This is not the place for submitting flashcart.
