### ISSUE TITLE
Supported Cartridge Not Detected: R4i Gold RTS Wi-Fi

### ISSUE THREAD

**Issue by wolfpacleader1986** [kitling/ntrboot_flasher#29]
Have a N3DS on custom firmware. Ran the Acekard Flasher which is supposed to work with the card(the nds file), and I get a message that the cartridge is not supported. Just bought it a few days ago and it's a legit cart.

**Comment by hedgeberg** [comment]
This doesn't make any sense, what do you mean the nds file? This tool doesn't use nds files. What cart? You said you bought it a few days ago but how do you know it's "legit"? Where did you buy it? We need a lot more information. Please provide the cart's Chip ID and hw rev as listed when trying to dump using this tool, as well as a link to where the cart was purchased and if possible pictures of the circuit board inside the cart's plastic.

**Comment by wolfpacleader1986** [comment]
Bought it from dsflashcart.com. I know it's legit because it had the authenticity holofoil sticker on the back. It's the R4i Gold RTS Wi-Fi. Chip ID is 000007C2. HW Rev is FFFFFFFF.

Originally used the NDS file for the single system method, but it doesn't work on your custom firmware tool either.

**Comment by Juanito9001** [comment]
Can you upload photos?? Specially of the PCB

_Enviado desde mi Samsung SM-G610M usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wolfpacleader1986** [comment]
I also forgot to mention, the code comes up as legitmate.

**Comment by wolfpacleader1986** [comment]
What file host for the pictures?

**Comment by kitling** [comment]
The cart with the label 'Wi-Fi' is not currently supported. See https://github.com/kitling/flashcart_core/issues/14
