### ISSUE TITLE
Version 0.1.3 show wrong version number

### ISSUE THREAD

**Issue by nuimk** [kitling/ntrboot_flasher#30]
`ntrboot_flasher.firm` downloaded from latest release show wrong version number.
Should be bumped to 0.1.3 but still 0.1.2.

**Comment by weirdal3333** [comment]
I can verify this, it's very confusing.

**Comment by hedgeberg** [comment]
This is a minor fix, but we can't exactly patch it in this release without making a new release. I'm going to leave this open so we remember to update it next time, and for now i think it will likely remain unfixed. Thanks for letting us know.
