### ISSUE TITLE
0.1.3 crash.

### ISSUE THREAD

**Issue by Siogenon** [kitling/ntrboot_flasher#31]
Hello.
The new release (0.1.3) crash when i start ( 3DS just shut off) ntrboot_flasher. Tried on N3DS ( luma ) and 2DS ( luma too). No error, just shut off.

**Comment by hedgeberg** [comment]
What did you do to launch it? You have b9s installed, right? What happens when you try to launch it from the luma chainlauncher specifcally? Can you post pictures of each screen?

**Comment by Siogenon** [comment]
I start it with LUMA3DS chainloader only, i take picture and send u after.

**Comment by Hikari-chin** [comment]
Can't reproduce, you're probably using an old version of boot9strap.

**Comment by Siogenon** [comment]
Thank's ! Problem solver, B9S just updated.
