### ISSUE TITLE
R4i clone not supported

### ISSUE THREAD

**Issue by hectortillo** [kitling/ntrboot_flasher#32]
Mi R4i clone doesnt work with any version of ntr_boot flasher.  Mine is a rare version. There are the pics[
![20170825_081232](https://user-images.githubusercontent.com/6589032/29715596-a5ae47de-896d-11e7-8dba-9838536658c0.jpg)
![20170825_081250](https://user-images.githubusercontent.com/6589032/29715606-b5be0966-896d-11e7-9458-0e47e4d2a276.jpg)
![20170825_081343](https://user-images.githubusercontent.com/6589032/29715614-bd27da92-896d-11e7-811d-d471ec2be3e8.jpg)

](url)

**Comment by dark-samus** [comment]
this is a completely different card from any I've seen so far. In the future, please [read the README](https://github.com/kitling/ntrboot_flasher#planned-supportcommunity-involvement)
