### ISSUE TITLE
r4 sdhc dual core 2016 support

### ISSUE THREAD

**Issue by SaikoPikachuu** [kitling/ntrboot_flasher#35]
i have this flashcard lying about and waswondering if support for it was gonna be added. i can post pictures if necessary and im sorry if this is a pointless post as im not sure what version in the flashcart core entails. thanks:)

**Comment by dark-samus** [comment]
read the readme

**Comment by kitling** [comment]
https://github.com/kitling/flashcart_core/issues/6
