### ISSUE TITLE
I think the r4idsn has the same chip like the R4i Gold 3DS RTS

### ISSUE THREAD

**Issue by pandavova** [kitling/ntrboot_flasher#4]
I tryed to dump the Flash of my r4idsn and got this:

![](http://i.imgur.com/VrTos5A.jpg)
![](https://i.imgur.com/czkq9WZ.jpg)

Should i try to inject ntrboothax?

**Comment by kitling** [comment]
I'd say give it a try! I'm not quite sure what all carts fall under the 'R4i 3DS Gold' umbrella yet. If it doesn't work, then you *should* be able to restore the backup.

Just in case, you should find a firmware updater that works for your cart, and post it here if it doesn't work and you can't restore.

**Comment by pandavova** [comment]
Done it (like some hours ago, backing up the r4idsn worked and flashing back too), installed sighax on my bricked 3DS XL, did a CTRtransfer, updated my 3DS with the recovery mode and have now a working 3DS XL again!
(But the plastic thing at the touch screen ribbon connector broke,now the colors on the touchscreen are not normal :( )

**Comment by kitling** [comment]
GG! Glad that it worked for you.
