### ISSUE TITLE
[DSTT] M29W400B is compatible, datasheets is the same as M29W400T

### ISSUE THREAD

**Issue by annson24** [kitling/ntrboot_flasher#42]
3 DSTTs I have have flashchips of ST M29W400B. I've successfully injected ntrboot on 2 out of 3 of them. The one that didn't worked had hardware problems anyway since it was really old and was collecting dust; even after cleaning it's still going haywire.

Anyway, checking online, seems like M29W400B and M29W400T has the same datasheet yet M29W400T was listed in the unsupported section.

http://pdf.datasheetcatalog.com/datasheet/SGSThomsonMicroelectronics/mXttvuu.pdf

**Comment by HandsomeMatt** [comment]
You're correct, a lot of the "unsupported" carts are from another program called DsttFlashWriter. I didn't have the time to check every single flash chip.

I've committed locally to add support for that chip and a few others, it'll be pushed out later today.

Can you post in flashcart_core in the future for flashcart specific stuff, thank you.

**Comment by annson24** [comment]
Yes sir, just saw your thread there. Will post there after testing more chips.
