### ISSUE TITLE
MX29LV320 doesn't work.

### ISSUE THREAD

**Issue by mark201200** [kitling/ntrboot_flasher#43]
I have a DSTT clone, it uses the MX29LV320CBTC-90G chip.
I've checked the [datasheet](https://github.com/kitling/ntrboot_flasher/files/1281923/datasheet.pdf) and it should be supported, but when I try to flash NTRBoot it says Flashcart setup failed.

**Comment by Shinigati** [comment]
I don't know if this will help but it did help me with my ak2i clone, if you have access to cfw or a nds/dsi try using the dsi flasher rom first. My ak2i was detected as not compatible in v 1.3 until i flashed it using the rom then it would let me dump inject or restore.

**Comment by mark201200** [comment]
Can someone compile a version of the installer that treats every card as a DSTT with a MX29LV320 ( ID: 0xA7C2 ) chip?

**Comment by HandsomeMatt** [comment]
Please keep flashcart specific stuff in https://github.com/kitling/flashcart_core/
