### ISSUE TITLE
Minor rendering issue.

### ISSUE THREAD

**Issue by zoogie** [kitling/ntrboot_flasher#44]
When the progress bar is filling up, the white % indicator doesn't clear old values which "smears"  and obscures readability. Once the yellow "filled" part passes the midway point, the value starts to render correctly.

**Comment by Committee** [comment]
I think that is part of the release notes:

Known Bug:

The progress bar percentages updates over top of itself without erasing, meaning that the numbers will probably become unreadable at some point. Didn't have time to fix this tonight, but we wanted to get proper DSTT support out ASAP.

**Comment by zoogie** [comment]
Ok, I'll lock this then.
