### ISSUE TITLE
One Time Ntrboot Flasher for DSTWO?

### ISSUE THREAD

**Issue by AlexS2412** [kitling/ntrboot_flasher#46]
i was told that its possible but the cart just cant be restored? I have more than one dstwo (3 to be exact) and would be more than willing to turn one into a permanent ntrboothax cart if you would be kind enough to supply a build to test.

**Comment by kitling** [comment]
Erm, I'm pretty sure that isn't the issue. In any case, there's already an open issue on flashcart_core about this cart.
