### ISSUE TITLE
In version 2.0, progress bar is ugly until green bar passes ~50%

### ISSUE THREAD

**Issue by fryfrog** [kitling/ntrboot_flasher#49]
During reading or writing, the numbers appear to draw over themselves and eventually just become a block of pixels. Once the green bar passes it, everything is fine.

**Comment by Hikari-chin** [comment]
If you had read the release notes, you would have seen this was already marked as a known bug.

**Comment by fryfrog** [comment]
So it was, sorry for reporting a known issue. :)
