### ISSUE TITLE
Build Error (MacOS): prototype for 'void Flashcart::showProgress(uint32_t, uint32_t, const char*)' does not match any in class 'Flashcart'

### ISSUE THREAD

**Issue by DayVeeBoi** [kitling/ntrboot_flasher#52]
Hi, anybody know what's going wrong here? It compiled fine in the past (although I can't rule out something incorrect in my PATH). I started to get the error after the last commit but I haven't tried to build in between. Thanks for any help, it's appreciated.
![screen shot 2017-09-27 at 9 47 00 am](https://user-images.githubusercontent.com/4130984/30917050-fa91d1a2-a368-11e7-9193-d2346765deb3.png)

**Comment by HandsomeMatt** [comment]
Looks like your flashcart_core submodule is old.

**Comment by DayVeeBoi** [comment]
Excellent, thanks that is exactly what was wrong. The solution for anyone else that is looking is
`git submodule update --remote`
