### ISSUE TITLE
Error with DSTT 9089

### ISSUE THREAD

**Issue by HWNJ** [kitling/ntrboot_flasher#61]
Just like happen to the user on issue https://github.com/kitling/ntrboot_flasher/issues/58 my DSTT stops at 99% reading.

I see it is on the flashcarts that should probably work, but you have no specific datasheet for it.
I make a dump of my card's firmware:
[Download from Github](https://github.com/kitling/ntrboot_flasher/files/1364686/DSTT.-.9089.-.INTEL.28F160B3T.zip)
[Download from Zippyshare](http://www98.zippyshare.com/v/cXAbq8Oj/file.html)
I hope it helps you to give full compatibility with this card. As I said, it is a DSTT - 9089 - INTEL 28F160B3T

I will try your debug builds from:
https://up1.secretalgorithm.com/#3Ai8X-28PPWGVysaMqmDUg
https://up1.secretalgorithm.com/#xgeexFwlDf0M3WFKXGCZDg
but I do not have high hopes on them. Will tell here if they works.....

**Comment by HWNJ** [comment]
The debug builds did not worked.
I post some reports on issue https://github.com/kitling/ntrboot_flasher/issues/58 
Anyway, here's a copy of them:
[Logs, info, pics and a videos from 6e9d-dirty and 2484-dirty](https://github.com/kitling/ntrboot_flasher/files/1366234/ntrboot.zip)

**Comment by kitling** [comment]
Actually belongs in https://github.com/kitling/flashcart_core/issues/56, where a bunch of other people are having the same issue.
