### ISSUE TITLE
[Request] Booting a file that isn't called boot.firm

### ISSUE THREAD

**Issue by lavanoid** [kitling/ntrboot_flasher#73]
I tried using this today, using my R4i-SDHC RTS. Flashing went fine and I am able to backup/restore the card without any issues. However, my 3DS already has been modified to run B9S, so I have no idea what is launching the boot.firm, either it's B9S or NTRBoot.

I just wanted to test to see if my flashcard is indeed working with ntrboot properly. Is there a possibility of being able to boot a file called `boot_ntr.firm` instead?

**Comment by HandsomeMatt** [comment]
ntrboot_flasher only flashes Boot9Strap onto an ntr card, what that boots is dependent on what boot9strap wants to launch, not ntrboot_flasher.

Compile your own version of https://github.com/SciresM/boot9strap if you want to change the booted file.
